// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBFi10wa-UpyZw9xKkKgpfgH0iiIdaxGI',
    appId: '1:804757653767:web:0786d3f602f45f9bbb9da2',
    messagingSenderId: '804757653767',
    projectId: 'kochurequiz',
    authDomain: 'kochurequiz.firebaseapp.com',
    storageBucket: 'kochurequiz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3d0aOE14Wooo6mcP_TImeFNX0dFRF5b0',
    appId: '1:804757653767:android:3b5c794fa502fcecbb9da2',
    messagingSenderId: '804757653767',
    projectId: 'kochurequiz',
    storageBucket: 'kochurequiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1t04MEA2VmgEN_G9tPZoo9_HitkGylDI',
    appId: '1:804757653767:ios:35fa5542082d9694bb9da2',
    messagingSenderId: '804757653767',
    projectId: 'kochurequiz',
    storageBucket: 'kochurequiz.appspot.com',
    iosClientId: '804757653767-sg9o9hqb1rtd4t4qgfpd2tltegas7spt.apps.googleusercontent.com',
    iosBundleId: 'com.example.kochureQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1t04MEA2VmgEN_G9tPZoo9_HitkGylDI',
    appId: '1:804757653767:ios:35fa5542082d9694bb9da2',
    messagingSenderId: '804757653767',
    projectId: 'kochurequiz',
    storageBucket: 'kochurequiz.appspot.com',
    iosClientId: '804757653767-sg9o9hqb1rtd4t4qgfpd2tltegas7spt.apps.googleusercontent.com',
    iosBundleId: 'com.example.kochureQuizApp',
  );
}
